### PR TITLE
Fixes #83 #82 #60 #58 #27 #25 or pretty much everything

### LINKED ISSUE #60: VideoLibrary stop working well
I think something is wrong, all my apps that use VideoLibrary for download videos stop working unexpectedly when someone try to download any video... This is the error:

> Se proporcionó un URI de solicitud no válido. El URI de solicitud debe ser un URI absoluto o debe establecerse BaseAddress.
**Translation**:
> An invalid request URI was provided. The request URI must be an absolute URI or BaseAddress must be set.

Any idea?

### LINKED ISSUE #83: Broken
It appears the majority of YouTube content is broken, the URLs this code returns issue an HTTP 403. 

Perhaps this is for only for video that is monetized?

Rarely a video works with this software.

### PR DESCRIPTION
**Pull request by hig-dev**
This fixes a lot of issues. I also removed the property for URI because you shouldn't do heavy operations which can cause exceptions in properties. Use GetUriAsync() instead.

### CODE REVIEW

**Comment by TheLordAndrew** [comment]
This should be merged in order to fix issues that more than one user has had

**Comment by 9kon** [comment]
Thanks buddy it works great for UWP but on WP 8.1 i get a 3 

> Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.ni.dll

 when i try and use. its on 
`var video = youTube.GetVideo(c);`

**Comment by hig-dev** [comment]
Fixed YouTube Decryption again

**Comment by omansak** [comment]
works

**Comment by sommmen** [comment]
Want to use this library? Fork this and recompile. Fixes all. @jamesqo please merge this!

**Comment by UnderKoen** [comment]
getting An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set. again :(

**Comment by dennismi** [comment]
I have traced the error down to downloading the jsPlayer. I think they may have change the location of the js library, and made a httpreferer requirement. (the last part is just speculation from my part - because i get an http 403 when trying to d/l the library manually)

**Comment by akcorp2003** [comment]
For me, this PR fixes the issues for invalid request URI. I haven't encountered an error yet but this is just using videos that I wasn't able to download before. Really hoping this PR gets merged regardless!

**Comment by massimocode** [comment]
This PR doesn't compile for me. The compat and debug projects don't compile, only the main project. @hig-dev can you rebase over master and fix the compilation? Also I think it might be better to keep Uri as a property. I know it may not be best practice, but I feel your commit is doing too many things.

Great job on fixing the issues though 👍

**Comment by massimocode** [comment]
I tried using this on the train with spotty connectivity and it basically hanged whilst downloading the video, no exception thrown. I don't know if that's because of this PR or if it's like that in master.

**Comment by i3arnon** [comment]
Hey @hig-dev. After taking over this repo I'm interested in trying to merge your changes in. Are you interested as well?
If so, can you please rebase on master, or allow me to edit your branch (or both :))?
I can't remove the `Uri` property as it will be a breaking change, but i can maybe mark it as obsolete of there are better options.

**Comment by hig-dev** [comment]
Hey @i3arnon I'm glad that this is maintained again. I will re-add the Uri property as an obsolete property and rebase.

**Comment by hig-dev** [comment]
I did not test the new commits but I think it should work. Just say if you want changes.

**Comment by hig-dev** [comment]
@i3arnon Will you merge the PR?

**Comment by i3arnon** [comment]
@hig-dev Sorry for the long wait. I finally have some time to look at it.
I'm going over the code and I have some changes in mind. Are you fine with me doing them directly on your branch?
If so can you allow edits from maintainers on this PR (https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by hig-dev** [comment]
@i3arnon That's great. I already did allow edits from maintainers.

**Comment by dkroye** [comment]
I've been using this branch with success for about a month. Sometime in the last week or so downloading with GetBytes() / GetBytesAsync() has slowed dramatically, about 10x or greater. @hig-dev Any ideas why that might've happened?

Edit: It looks like GetBytesAsync() is now failing. I'll report if I can determine the source of the issue.

**Comment by mhnewsuk** [comment]
@i3arnon Hey, any chance we could get this merged anytime soon? We've been waiting for a couple of months now. I'm still using a custom build of hig-dev's fork cause the main build doesn't work with a lot of videos!

**Comment by hig-dev** [comment]
I replaced the decryption method completely with the method which https://github.com/Tyrrrz/YoutubeExplode uses because the decryption doesn't work properly since Feb 1. 2018. The new method also looks much cleaner.

**Comment by dkroye** [comment]
You're very efficient. I appreciate it.

Regarding the slowdown I've experienced, have you any theories? Interestingly I've discovered one video that downloads quickly, and a difference is every other video download loads System.Text.RegularExpressions.dll and System.Globalization.dll while that one does not. Hmm.

**Comment by i3arnon** [comment]
Hey @hig-dev,
I might be wrong (and please correct me if I am) but as far as I understand I can't include source code under LGPL in this library which is under BSD-2. LGPL is less permissive than BSD/MIT/etc (https://softwareengineering.stackexchange.com/questions/47323/can-i-use-an-lgpl-licenced-library-in-my-commercial-app).

I realize the latest stable version (1.3.5) has some issues but as far as I know the current code in master (and in the 1.3.6-alpha nuget) works. I can't manage to find a youtube link that breaks it (I would appreciate to get some though :)).
However, I do intend on refactoring the signature decryption part a bit on my own.

**Comment by wesbyte** [comment]
Hello, 
Thanks for your awesome work, the dll doesn't work for some videos
it gives this error "The media could not be loaded, either because the server or network failed or because the format is not supported."
ex; https://www.youtube.com/watch?v=8m8lflI3clQ

Please advice.

**Comment by omansak** [comment]
Update regex :  
`c&&d.set(b,encodeURIComponent(fv(decodeURIComponent(c))));return d};`
we must find 'fv' with regex  `\bc\s*&&\s*d\.set\([^,]+\s*,[^(]*\(([a-zA-Z0-9$]+)\( `

we must replace this line https://github.com/i3arnon/libvideo/blob/586421e0f39367d79b437daa517d3c008f0d20eb/src/libvideo/YouTubeVideo.Decrypt.cs#L13 with code in below : 

`private static readonly Regex DecryptionFunctionRegex = new Regex(@"\bc\s*&&\s*d\.set\([^,]+\s*,[^(]*\(([a-zA-Z0-9$]+)\(");`

**Comment by SaadArdati** [comment]
Is this ever going to get merged?

**Pull request closed without merging**
