### PR TITLE
Fixed New Decrypt

### PR DESCRIPTION
**Pull request by omansak**
```
var TK={
  xa:function(a,b){
    var c=a[0];
    a[0]=a[b%a.length];
    a[b%a.length]=c}, 
  "do":function(a){
    a.reverse()
  }, 
  BH:function(a,b){
    a.splice(0,b)
  }};
{
  UK = function(a) {
    a = a.split("");
    
    TK.BH(a, 2);
    TK.xa(a, 13);
    TK.BH(a, 1);
    TK["do"](a, 37);
    TK.BH(a, 1);
    TK.xa(a, 69);
    TK["do"](a, 36);
    return a.join("");
  };
}
```

### CODE REVIEW

**Comment by omansak** [comment]
#97 Fixed

**Comment by omansak** [comment]
, i am working on new decrypt script

```
var TK =
{
    p8: function (a, b) {
        a.splice(0, b)
    },
    z6: function (a, b) {
        var c = a[0];
        a[0] = a[b % a.length];
        a[b % a.length] = c
    },
    d4: function (a) {
        a.reverse()
    }
};
UK=function(a){
    a=a.split("");
    TK.z6(a,23);
    TK.p8(a,2);
    TK.d4(a,55);
    TK.z6(a,6);
    return a.join("")
}
```

**Comment by Gr3gorywolf** [comment]
Good luck!

**Comment by omansak** [comment]
@Gr3gorywolf Please test

**Comment by Gr3gorywolf** [comment]
Meeeeeeeen you are a genius its working again God bless you

**Comment by Gr3gorywolf** [comment]
i will follow you

**Comment by LordFancyEagle** [comment]
I have tried this fix and it has not worked.i still get the same errors.

**Comment by omansak** [comment]
Use #98 not #97

**Comment by Gr3gorywolf** [comment]
Man it works!! thanks again but i will suggest you an idea to implement. the only thing that i see that you always change is the regex string i guess that you constantly change this because of youtube decrypt algorithm but i guess that this will be more easier if you host a file containing the string and every time that you will decrypt download that string and apply. by this way you can can update the regex string and we dont need to recompile the library for example i have an app based on that and imagine that i need to post an update each time that youtube change the decrypt even i will try to implement that and i want to know your opinion :V

**Comment by Gr3gorywolf** [comment]
the last commit worked perfectly but takes a lot of time to get the info :( can you fix it? @omansak if you can fix it you will be our hero

**Comment by omansak** [comment]
#103 test and feedback.

**Comment by omansak** [comment]
@Gr3gorywolf  added a basic webservice for regex

**Pull request closed without merging**
