### PR TITLE
Fixed Some Bugs 

### PR DESCRIPTION
**Pull request by omansak**
#124

### CODE REVIEW

**Comment by omansak** [comment]
#133 Fixed Youtube Signature Decrypt

**Comment by ColorTwist** [comment]
I'll note that I tried the new update, pretty neat and works,  however, if 'DFuctionRegexService ' URL is incorrect or website that contains the Regex-string is offline you'll get an error, of course.
Is there a way that if static Regex-string is incorrect then try to get Regex-string from URL and use that URL instead?

**Comment by omansak** [comment]
@ColorTwist i pushed new version

**Comment by ColorTwist** [comment]
Looks good from a short test.

**Comment by i3arnon** [comment]
@omansak Hey, will you be interested in taking over this project and library?

**Comment by omansak** [comment]
@i3arnon yes sure,i would be glad

**Comment by i3arnon** [comment]
@omansak Can you follow me on twitter so we can DM: https://twitter.com/i3arnon

**Pull request merged**
