### PR TITLE
Update Decrypt Regex

### PR DESCRIPTION
**Pull request by omansak**
Fixed for new youtube encodes.
Added dynamic service for decrypt

### CODE REVIEW

**Comment by SoftwareMagicIT** [comment]
Error KeyDictionaryNotFoundException in Query.cs

This is a link of video: https://www.youtube.com/watch?v=-Gb7tI7zL9E

**Comment by Gr3gorywolf** [comment]
Omg!!!!! Man you implemented the  webservice now  everything will be more easier and now the only thing  that  you need to do is to chang e the content in your hosted webpage. good job!

**Comment by omansak** [comment]
@Gr3gorywolf  updated service and my service is not reliable pls use your own service

**Comment by Gr3gorywolf** [comment]
@omansak Host the html on github pages that brings you a really good bandwidth

**Comment by omansak** [comment]
@Gr3gorywolf azurewebsite avg is 95ms , github is avg 60ms for get it so it not need github

**Comment by Gr3gorywolf** [comment]
well then i dont have any other idea actually but i guess that this will works well

**Comment by Elite** [comment]
@oman Host a txt file and have it behind cloudflare, problem solved.

**Comment by ghost** [comment]
please update the nuget

**Pull request closed without merging**
