### PR TITLE
Update Json.cs

### PR DESCRIPTION
**Pull request by sepp89117**
Fixed an error when '{' or '}' is inside a string.
See https://github.com/omansak/libvideo/issues/239

### CODE REVIEW

**Comment by sepp89117** [comment]
Added Age-Restriction-Bypass too

**Comment by omansak** [comment]
can we need `<TargetFramework>netstandard2.0</TargetFramework>` ?

**Comment by sepp89117** [comment]
Netstandard 2.0 is required for class `HttpWebRequest`, for the Age Bypass. It is not required for the bug fix in json.cs

**Comment by omansak** [comment]
i merged JSON fix but i reverted Age Bypass because i need a little think about of build-in api key

**Pull request merged**
